[platformio]
default_envs = lilygo-t-display-s3
boards_dir = ./boards

[env:m5stickc-plus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.f_cpu = 160000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5StickCPlus
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-displays3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_LILYGO_T_DISPLAY_S3
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=5
    -DTFT_WR=8
    -DTFT_RD=9
    -DTFT_D0=39
    -DTFT_D1=40
    -DTFT_D2=41
    -DTFT_D3=42
    -DTFT_D4=45
    -DTFT_D5=46
    -DTFT_D6=47
    -DTFT_D7=48
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
build_src_filter = +<*> +<buddies/>
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    mathertel/OneButton @ ^2.5.0
